// Generated by CoffeeScript 1.8.0
(function() {
  var Mpeg1Muxer, STREAM_MAGIC_BYTES, VideoStream, events, util, ws;

  ws = require('ws');

  util = require('util');

  events = require('events');

  Mpeg1Muxer = require('./mpeg1muxer');

  STREAM_MAGIC_BYTES = "jsmp";

  VideoStream = function(options) {
    this.name = options.name;
    this.streamUrl = options.streamUrl;
    this.width = options.width;
    this.height = options.height;
    this.wsPort = options.wsPort;
    this.inputStreamStarted = false;
    this.stream = void 0;
    this.startMpeg1Stream();
    this.pipeStreamToSocketServer();
    return this;
  };

  util.inherits(VideoStream, events.EventEmitter);

  VideoStream.prototype.startMpeg1Stream = function() {
    var self;
    this.mpeg1Muxer = new Mpeg1Muxer({
      url: this.streamUrl
    });
    self = this;
    if (this.inputStreamStarted) {
      return;
    }
    this.mpeg1Muxer.on('mpeg1data', function(data) {
      return self.emit('camdata', data);
    });
    return this;
  };

  VideoStream.prototype.pipeStreamToSocketServer = function() {
    var self;
    self = this;
    this.wsServer = new ws.Server({
      port: this.wsPort
    });
    this.wsServer.on("connection", function(socket) {
      return self.onSocketConnect(socket);
    });
    this.wsServer.broadcast = function(data, opts) {
      var i, _results;
      _results = [];
      for (i in this.clients) {
        if (this.clients[i].readyState === 1) {
          _results.push(this.clients[i].send(data, opts));
        } else {
          _results.push(console.log("Error: Client (" + i + ") not connected."));
        }
      }
      return _results;
    };
    return this.on('camdata', function(data) {
      return self.wsServer.broadcast(data);
    });
  };

  VideoStream.prototype.onSocketConnect = function(socket) {
    var self, streamHeader;
    self = this;
    streamHeader = new Buffer(8);
    streamHeader.write(STREAM_MAGIC_BYTES);
    streamHeader.writeUInt16BE(this.width, 4);
    streamHeader.writeUInt16BE(this.height, 6);
    socket.send(streamHeader, {
      binary: true
    });
    console.log(("" + this.name + ": New WebSocket Connection (") + this.wsServer.clients.length + " total)");
    return socket.on("close", function(code, message) {
      return console.log(("" + this.name + ": Disconnected WebSocket (") + self.wsServer.clients.length + " total)");
    });
  };

  module.exports = VideoStream;

}).call(this);
